---
deployment:
    tasks:
        - export DEPLOYPATH=/home/admin2015tennis/public_html
        - /bin/cp -R public $DEPLOYPATH
        - /bin/cp index.php $DEPLOYPATH
        - /bin/cp server.php $DEPLOYPATH
